"""
ForenSight V4 — Standard Artifact Contract

Defines metadata schema for forensic artifacts generated by analytical engines:
heatmaps, plots, spatial masks, frequency spectra, tabular summaries, and derived images.
Integrates directly with the existing storage/artifact serving and investigation graph.
"""

from enum import Enum
from typing import Optional, Dict, Any
from datetime import datetime, timezone
from pydantic import BaseModel, Field


class ArtifactType(str, Enum):
    HEATMAP = "HEATMAP"
    PLOT = "PLOT"
    VISUALIZATION = "VISUALIZATION"
    MASK = "MASK"
    SPECTRUM = "SPECTRUM"
    TABLE = "TABLE"
    JSON = "JSON"
    DERIVED_IMAGE = "DERIVED_IMAGE"


class EngineArtifactMetadata(BaseModel):
    """
    Metadata describing a forensic artifact generated during engine execution.
    """
    artifact_id: str = Field(..., description="Unique identifier for the artifact.")
    evidence_id: int = Field(..., description="Parent evidence ID.")
    analysis_id: Optional[int] = Field(None, description="Parent analysis execution record ID.")
    engine_id: str = Field(..., description="ID of the engine that generated this artifact.")
    engine_version: str = Field(..., description="Version of the engine that produced the output.")
    artifact_type: ArtifactType = Field(..., description="Classification of the artifact.")
    
    storage_path: str = Field(..., description="Relative storage path relative to storage root.")
    sha256_hash: str = Field(..., description="Cryptographic SHA-256 digest of the artifact file.")
    
    mime_type: str = Field("image/png", description="MIME content type.")
    width: Optional[int] = Field(None, description="Pixel width where applicable.")
    height: Optional[int] = Field(None, description="Pixel height where applicable.")
    
    parameters_used: Dict[str, Any] = Field(default_factory=dict, description="Parameters used to synthesize the artifact.")
    provenance_metadata: Dict[str, Any] = Field(default_factory=dict, description="Lineage metadata.")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Generation timestamp.")

    def to_legacy_artifact_dict(self) -> Dict[str, str]:
        """
        Formats artifact for storage inside Analysis.structured_findings['artifacts'].
        """
        return {self.artifact_id: self.storage_path}
