"""
ForenSight V4 — Normalized Observation Contract

Defines a standardized observation contract that integrates with the existing
EvidenceObservation database models, Fusion Normalizer (Rule 7B-v1),
and Correlation Engine.
"""

from typing import Optional, Dict, Any, List
from datetime import datetime, timezone
from pydantic import BaseModel, Field
from app.models.domain import EvidenceObservation


class NormalizedObservation(BaseModel):
    """
    Standardized empirical observation generated by a V4 forensic engine.
    Compatible with EvidenceObservation and Rule 7B-v1 Fusion pipeline.
    """
    evidence_id: int = Field(..., description="Target evidence database ID.")
    analysis_id: Optional[int] = Field(None, description="Parent analysis ID if persisted.")
    engine_id: str = Field(..., description="Originating forensic engine identifier.")
    engine_version: str = Field(..., description="Version of the engine that produced this observation.")
    
    status: str = Field("APPLIED", description="Execution status: APPLIED, NOT_APPLICABLE, FAILED.")
    observation_type: str = Field(..., description="Observation classification (e.g. COMPRESSION_ANOMALY, RESIDUAL_NOISE).")
    metric_name: str = Field(..., description="Primary metric identifier (e.g. MEAN_ERROR, DC_HIST_KURTOSIS).")
    
    raw_value: str = Field(..., description="Unscaled empirical value as a string representation.")
    normalized_value: Optional[float] = Field(None, description="Optional scaled metric in [0.0, 1.0].")
    
    direction: str = Field("informational", description="Directional indicator: elevated, consistent, or informational.")
    technical_reliability: str = Field("HIGH", description="Algorithmic reliability: HIGH, MEDIUM, CONDITIONAL.")
    
    result_data: Dict[str, Any] = Field(default_factory=dict, description="Detailed dictionary of empirical measurements.")
    parameters_used: Dict[str, Any] = Field(default_factory=dict, description="Parameters supplied to the engine.")
    
    applicability_rationale: Optional[str] = Field(None, description="Explanation of why method applied or did not apply.")
    interpretation: str = Field(..., description="Objective explanation of the observed physical/mathematical measurement.")
    limitations: List[str] = Field(default_factory=list, description="Methodological limitations governing this observation.")
    
    provenance: Dict[str, Any] = Field(default_factory=dict, description="Lineage metadata.")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Observation timestamp.")

    def to_domain_observation(self) -> EvidenceObservation:
        """
        Converts the normalized observation into the SQLAlchemy EvidenceObservation model
        for seamless database persistence.
        """
        limitations_str = " | ".join(self.limitations) if self.limitations else ""
        return EvidenceObservation(
            evidence_id=self.evidence_id,
            analysis_id=self.analysis_id or 0,
            modality=self.engine_id,
            observation_type=self.observation_type,
            metric_name=self.metric_name,
            raw_value=self.raw_value,
            normalized_value=self.normalized_value,
            direction=self.direction,
            technical_reliability=self.technical_reliability,
            interpretation=self.interpretation,
            limitations=limitations_str,
            created_at=self.created_at,
        )
