"""Initial Schema

Revision ID: aad6cb327d0d
Revises: 
Create Date: 2026-08-30 00:39:16.957063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aad6cb327d0d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('safe_metadata', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_case_id'), 'audit_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_id'), 'audit_events', ['id'], unique=False)
    op.create_index(op.f('ix_audit_events_timestamp'), 'audit_events', ['timestamp'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_identifier', sa.String(), nullable=True),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('rule_version', sa.String(), nullable=True),
    sa.Column('report_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('artifact_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_case_id'), 'reports', ['case_id'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_report_identifier'), 'reports', ['report_identifier'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('investigation_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_identifier', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_cases_case_identifier'), 'investigation_cases', ['case_identifier'], unique=True)
    op.create_index(op.f('ix_investigation_cases_id'), 'investigation_cases', ['id'], unique=False)
    op.create_index(op.f('ix_investigation_cases_title'), 'investigation_cases', ['title'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_identifier', sa.String(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('stored_path', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('sha256_hash', sa.String(), nullable=True),
    sa.Column('image_format', sa.String(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['investigation_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_evidence_identifier'), 'evidence', ['evidence_identifier'], unique=True)
    op.create_index(op.f('ix_evidence_id'), 'evidence', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_sha256_hash'), 'evidence', ['sha256_hash'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_identifier', sa.String(), nullable=True),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('analysis_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('structured_findings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_analysis_identifier'), 'analyses', ['analysis_identifier'], unique=True)
    op.create_index(op.f('ix_analyses_analysis_type'), 'analyses', ['analysis_type'], unique=False)
    op.create_index(op.f('ix_analyses_id'), 'analyses', ['id'], unique=False)
    op.create_table('evidence_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('rule_version', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('contributing_observations', sa.JSON(), nullable=True),
    sa.Column('contributing_relations', sa.JSON(), nullable=True),
    sa.Column('limitations', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_assessments_evidence_id'), 'evidence_assessments', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_evidence_assessments_id'), 'evidence_assessments', ['id'], unique=False)
    op.create_table('analysis_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_identifier', sa.String(), nullable=True),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('analysis_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('queued_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('safe_error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_jobs_analysis_type'), 'analysis_jobs', ['analysis_type'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_evidence_id'), 'analysis_jobs', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_id'), 'analysis_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_job_identifier'), 'analysis_jobs', ['job_identifier'], unique=True)
    op.create_table('evidence_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('modality', sa.String(), nullable=True),
    sa.Column('observation_type', sa.String(), nullable=True),
    sa.Column('metric_name', sa.String(), nullable=True),
    sa.Column('raw_value', sa.String(), nullable=True),
    sa.Column('normalized_value', sa.Float(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('technical_reliability', sa.String(), nullable=True),
    sa.Column('interpretation', sa.String(), nullable=True),
    sa.Column('limitations', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_observations_analysis_id'), 'evidence_observations', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_evidence_observations_evidence_id'), 'evidence_observations', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_evidence_observations_id'), 'evidence_observations', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_observations_modality'), 'evidence_observations', ['modality'], unique=False)
    op.create_table('evidence_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('observation_a_id', sa.Integer(), nullable=True),
    sa.Column('observation_b_id', sa.Integer(), nullable=True),
    sa.Column('relation_type', sa.String(), nullable=True),
    sa.Column('strength', sa.String(), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('limitations', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['observation_a_id'], ['evidence_observations.id'], ),
    sa.ForeignKeyConstraint(['observation_b_id'], ['evidence_observations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_relations_evidence_id'), 'evidence_relations', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_evidence_relations_id'), 'evidence_relations', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_relations_observation_a_id'), 'evidence_relations', ['observation_a_id'], unique=False)
    op.create_index(op.f('ix_evidence_relations_observation_b_id'), 'evidence_relations', ['observation_b_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_relations_observation_b_id'), table_name='evidence_relations')
    op.drop_index(op.f('ix_evidence_relations_observation_a_id'), table_name='evidence_relations')
    op.drop_index(op.f('ix_evidence_relations_id'), table_name='evidence_relations')
    op.drop_index(op.f('ix_evidence_relations_evidence_id'), table_name='evidence_relations')
    op.drop_table('evidence_relations')
    op.drop_index(op.f('ix_evidence_observations_modality'), table_name='evidence_observations')
    op.drop_index(op.f('ix_evidence_observations_id'), table_name='evidence_observations')
    op.drop_index(op.f('ix_evidence_observations_evidence_id'), table_name='evidence_observations')
    op.drop_index(op.f('ix_evidence_observations_analysis_id'), table_name='evidence_observations')
    op.drop_table('evidence_observations')
    op.drop_index(op.f('ix_analysis_jobs_job_identifier'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_id'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_evidence_id'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_analysis_type'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_index(op.f('ix_evidence_assessments_id'), table_name='evidence_assessments')
    op.drop_index(op.f('ix_evidence_assessments_evidence_id'), table_name='evidence_assessments')
    op.drop_table('evidence_assessments')
    op.drop_index(op.f('ix_analyses_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_analysis_type'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_analysis_identifier'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_evidence_sha256_hash'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_evidence_identifier'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_investigation_cases_title'), table_name='investigation_cases')
    op.drop_index(op.f('ix_investigation_cases_id'), table_name='investigation_cases')
    op.drop_index(op.f('ix_investigation_cases_case_identifier'), table_name='investigation_cases')
    op.drop_table('investigation_cases')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_reports_report_identifier'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_case_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_audit_events_timestamp'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_case_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
